date.timezone=UTC

extension_dir="H:/Users/Gui/AppData/Local/Microsoft/WinGet/Packages/PHP.PHP.8.3_Microsoft.Winget.Source_8wekyb3d8bbwe/ext"

extension=openssl
extension=curl
extension=fileinfo
extension=mbstring
extension=pdo_sqlite
extension=sqlite3
extension=zip
extension=pdo_pgsql
extension=pgsql

